In [1]:
import numpy as np

In [40]:
# Sigmoid function using numpy
def sigmoid(x):
  s=1/(1+np.exp(-x))
  return s

# x=2
x=np.array([5,2,7])
print("Output of Sigmoid Function :\n",sigmoid(x))

Output of Sigmoid Function :
 [0.99330715 0.88079708 0.99908895]


In [41]:
# implementing sigmoid_grad() function (gradient of sigmoid)
def sigmoid_grad(x):
  s=sigmoid(x)
  ds=s*(1-s)
  return ds

x=np.array([5,2,7])
print("Gradient of sigmoid :\n",sigmoid_grad(x))

Gradient of sigmoid :
 [0.00664806 0.10499359 0.00091022]


In [29]:
#Implementing normalizeRows() to normalize the rows of a matrix
def normalizeRows(x):
  normalized_x = np.linalg.norm(x,axis=1,keepdims = True);
  x = x / normalized_x;
  return x;

x=np.array([[[2,4,6],[3,1,5],[8,4,9]]])
print("Normalized form of matrix : \n",normalizeRows(x))

Normalized form of matrix : 
 [[[0.22792115 0.69631062 0.50350881]
  [0.34188173 0.17407766 0.41959068]
  [0.91168461 0.69631062 0.75526322]]]


In [30]:
# implimenting the softmax function 
def softmax(x):
  exp_x = np.exp(x)
  normalized_x = np.linalg.norm(exp_x,axis=1,keepdims=True)
  output = exp_x / normalized_x
  return output

x=np.array([[[2,4,6],[3,1,5],[8,4,9]]])
print("Output of softmax function :\n",softmax(x))

Output of softmax function :
 [[[0.00247869 0.706669   0.04971716]
  [0.00673777 0.03518298 0.01828992]
  [0.99997423 0.706669   0.99859586]]]


In [39]:
def L1_loss(y,yh):
  loss=np.sum(np.abs(y-yh))
  return loss

y=np.array([1,1,0])
yh=np.random.randn(1,3)
print(yh)
print("L1 Loss : ",L1_loss(y,yh))

[[-0.17761308  0.83961381 -1.36834127]]
L1 Loss :  2.706340542139333
