<a href="https://colab.research.google.com/github/Rajatsharma2002/NeuralNetwork/blob/main/Pytorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [29]:
# creation of tensor
a=torch.randn(3,3)
a

tensor([[ 0.7662,  1.5147, -0.1911],
        [ 0.9566,  0.6175,  1.0918],
        [-0.1631, -0.9851, -1.2528]])

In [30]:
# manupulation of tensor
a[0][2]=5
a

tensor([[ 0.7662,  1.5147,  5.0000],
        [ 0.9566,  0.6175,  1.0918],
        [-0.1631, -0.9851, -1.2528]])

In [31]:
# deletion of tensor
del a

In [58]:
M1=torch.tensor([[1,2,3],[6,8,4],[9,4,6]])
print(f"Matrix M1 :\n{M1}") 

Matrix M1 :
tensor([[1, 2, 3],
        [6, 8, 4],
        [9, 4, 6]])


In [59]:
M2=torch.tensor([[6,4,1],[9,3,0],[7,2,8]])
print(f"Matrix M2 :\n{M2}") 

Matrix M2 :
tensor([[6, 4, 1],
        [9, 3, 0],
        [7, 2, 8]])


In [57]:
# matrix addition
result =torch.tensor([[0,0,0], [0,0,0], [0,0,0]])  
for i in range(len(M1)):    
  for j in range(len(M1[0])): 
    result[i][j] = M1[i][j] + M2[i][j] 
print(f"Addition of Matrix M1 and M2 : \n{result}")

Addition of Matrix M1 and M2 : 
tensor([[ 7,  6,  4],
        [15, 11,  4],
        [16,  6, 14]])


In [60]:
# matrix Subtraction
result =torch.tensor([[0,0,0], [0,0,0], [0,0,0]])  
for i in range(len(M1)):    
  for j in range(len(M1[0])): 
    result[i][j] = M1[i][j] - M2[i][j] 
print(f"Subtraction of Matrix M1 and M2 : \n{result}")

Subtraction of Matrix M1 and M2 : 
tensor([[-5, -2,  2],
        [-3,  5,  4],
        [ 2,  2, -2]])


In [56]:
# Matrix multiplication
result =torch.tensor([[0,0,0], [0,0,0], [0,0,0]])  
for i in range(len(M1)):    
  for j in range(len(M1[0])): 
    result[i][j] = M1[i][j] * M2[i][j] 
print(f"Multiplication of Matrix M1 and M2 : \n{result}")

Multiplication of Matrix M1 and M2 : 
tensor([[ 6,  8,  3],
        [54, 24,  0],
        [63,  8, 48]])


In [63]:
# Matrix transpose
result1=torch.tensor([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(M1)):
  for j in range(len(M1[0])):
    result1[j][i]=M1[i][j]
print(f"Transpose of Matrix M1 : \n{result1}")

result2=torch.tensor([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(M2)):
  for j in range(len(M2[0])):
    result2[j][i]=M2[i][j]
print(f"\nTranspose of Matrix M2 : \n{result2}")


Transpose of Matrix M1 : 
tensor([[1, 6, 9],
        [2, 8, 4],
        [3, 4, 6]])

Transpose of Matrix M2 : 
tensor([[6, 9, 7],
        [4, 3, 2],
        [1, 0, 8]])
